### ISSUE TITLE
Infinity code lens references

### ISSUE THREAD

**Issue by gavr123456789** [clojure-lsp/clojure-lsp-intellij#29] opened 2024-01-03 18:52 UTC
![image](https://github.com/clojure-lsp/clojure-lsp-intellij/assets/30507409/33482346-ccd7-4a10-8a5d-1d4acebb3b68)
Idea Ultimate 2023.3.2 
Plugin version: 1.14.2

**Comment by ericdallo** [comment] 2024-01-07 18:03
Looks like a problem with not cleaning lens after applying new ones, @gavr123456789 did you anything specific to repro that?

**Comment by gavr123456789** [comment] 2024-01-09 07:31
@ericdallo 
No, nothing specific, I have it after first time using the plugin, so I just disabled lens.

**Comment by ericdallo** [comment] 2024-01-09 11:19
Could you test if it happen sin Intellij Community?

**Comment by abreumatheus** [comment] 2024-02-27 18:15
@ericdallo  Confirmed also happening in Community Edition.
![Screenshot 2024-02-27 at 15 14 44](https://github.com/clojure-lsp/clojure-lsp-intellij/assets/13948812/d88f16dd-3fac-4db8-b760-f2ef7fbd0339)

**Comment by ericdallo** [comment] 2024-02-29 12:22
Thanks, I still can't repro the issue on any project (like [clojure-sample](https://github.com/ericdallo/clojure-sample)) so it makes harder to understand what's going on

**Comment by mefryar** [comment] 2024-03-01 00:25
I'm seeing the issue on [clojure-sample](https://github.com/ericdallo/clojure-sample), so I don't think it is project-specific. 
![image](https://github.com/clojure-lsp/clojure-lsp-intellij/assets/21371788/81aa9dcd-21a7-4e68-960e-7ad21dae9a7c)
> macOS 14.3.1
> IntelliJ IDEA 2023.3.4 (Community Edition)
> clojure-lsp-intellij 1.14.9

**Comment by abreumatheus** [comment] 2024-03-01 05:04
@ericdallo The common denominator here seems to be macOS. I think you're on linux, right @ericdallo?

**Comment by ericdallo** [comment] 2024-03-01 12:34
Yes, I can't see how this would affect, but yeah it 's a factor and I don't have any macos  to repro that

**Comment by ericdallo** [comment] 2024-03-07 20:44
Folks, finally, this bug should be fixed by #34, let me know if not.
Available on 2.0.0 version.

**Closed** 2024-03-07 20:45 UTC
Labels: bug
